### ISSUE TITLE
TMDb api key is public in the repo

### ISSUE THREAD

**Issue by henrikra** [mahadyC/movie-app-project#2]
Now in `api.ts` the api key is public to the whole wide world :D So we need to get rid of that. Right way to do this is to use [environment variables](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables)

So basically 
1. create `.env` file
2. put it to `.gitignore` so the api key is not in the repo
3. add note to README that developers who want to try out your code have to create this `.env` file and add their api key there

All information about this is in the link above :)

**Comment by mahadyC** [comment]
This issue was fixed in this PR https://github.com/mahadyC/movie-app-project/pull/3
